### ISSUE TITLE
Meaning of nagios_dont_blame is inverse of dont_blame_nrpe

### ISSUE THREAD

**Issue by rlaurika** [CSC-IT-Center-for-Science/ansible-role-nrpe#2]
The nagios_dont_blame setting sets dont_blame_nrpe in nrpe.cfg. It sets it so that when nagios_dont_blame is true, then dont_blame_nrpe is false and vice versa. This is a bit confusing.

**Comment by martbhell** [comment]
I agree!

a) I seems to have mixed nrpe and nagios quite freely in the variables names. This could be fixed normalized to become just nrpe_ perhaps?
b) Yes, let's set is so that if dont_blame_nrpe == True then set it to 1. I'll whip something up.

**Comment by martbhell** [comment]
Bad me. I never whipped something up. See #10

**Comment by rlaurika** [comment]
Addressed by #10 

Thanks @martbhell !
