### ISSUE TITLE
Allow management of nrpe.cfg

### ISSUE THREAD

**Issue by rlaurika** [CSC-IT-Center-for-Science/ansible-role-nrpe#6]
I discovered today that nrpe.cfg as installed via RPM has some hardcoded "example" configurations in place:

```
command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10
command[check_load]=/usr/lib64/nagios/plugins/check_load -r -w .15,.10,.05 -c .30,.25,.20
command[check_hda1]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1
command[check_zombie_procs]=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z
command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 150 -c 200
```

Even if you configure check_load separately in a different place, this configuration will override it and give you warnings for very light load.

It would be nice if we could manage nrpe.cfg via this role so that it would be possible to get rid of these "examples".

**Comment by rlaurika** [comment]
It looks like you can override where the templated config file will be placed and could overwrite the default nrpe.cfg file. However, the template does not contain the include_dir option, so also including config from an nrpe.d directory wouldn't work. There could also be a method for adding freeform configuration in the override template as a fallback for situations like this.

How about making a basic replacement for nrpe.cfg that could optionally be used to overwrite the system default one?

**Comment by rlaurika** [comment]
Party addressed by https://github.com/CSCfi/ansible-role-nrpe/pull/7

**Comment by martbhell** [comment]
#7 merged and seems to work. I'm happy with this change. Marginally better than templating over nrpe.cfg from upstream - no need to sync changes to upstream's version. Adding a freeform configuration option to the file would be good though. Added some related PRs: #8 and #9

**Comment by martbhell** [comment]
PRs merged. OK to close?

**Comment by rlaurika** [comment]
Yes - looks good to me.
